name: null_check_lint
version: 0.0.4
publish_to: none

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  analyzer: ^5.12.0
  analyzer_plugin: ^0.11.2
  custom_lint_builder: ^0.4.0
  logger: ^1.3.0

dev_dependencies:
  custom_lint:

dependency_overrides:
  custom_lint: 0.4.0
  custom_lint_core: ^0.4.0