name: null_check_lint_example
version: 0.0.3
publish_to: none

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  analyzer: ^5.0.0
  analyzer_plugin: ^0.11.2
  custom_lint_builder: ^0.4.0

dev_dependencies:
  custom_lint:

dependency_overrides:
  custom_lint: 0.4.0
  custom_lint_core: ^0.4.0